logs:improved crash logs during failure with keploy
keploy/java-sdk pull request #48
Opened 2022-09-11 14:14 UTC by gouravkrosx

Related issue: #45 

Signed-off-by: gouravkrosx <gouravgreatkr@gmail.com>

2022-09-12 05:23 UTC, Sarthak160 approved these changes

2022-09-12 13:04 UTC, slayerjain commented on api/src/main/java/io/keploy/service/GrpcService.java
> +            logger.error("failed to start test run, please check keploy logs", e);
this should be `keploy server logs` for added clarity.

2022-09-12 13:06 UTC, slayerjain commented on api/src/main/java/io/keploy/service/GrpcService.java
> +            logger.debug("response getting from simulate request: {}", resp);
`response got from simulate` here

2022-09-12 13:18 UTC, slayerjain requested changes
mostly LGTM

2022-09-13 08:46 UTC, gouravkrosx reviewed
Resolved the mentioned changes

2022-09-13 08:54 UTC, merged